use std::fs::File;
use std::io::{stdin, Write};

fn ask_name() -> String {
    println!("Enter the name for the checklist (will have .txt appended): ");
    let mut input = String::new();

    stdin().read_line(&mut input).expect("Invalid input");
    return input.trim().to_string();
}

fn get_file_name(args: Vec<String>) -> String {
    let file_name: String;
    if args.len() > 2 {
        file_name = args[2].to_string();
    } else {
        file_name = ask_name();
    }
    return String::from(file_name + ".txt");
}

fn init_file(file_name: String) -> std::fs::File {
    let mut file = File::create(file_name).expect("Error occurred while creating file.");
    file.write_all(
        b"This is an auto-generated checklist made by todo-tracker.\n\nDo not edit this file.",
    )
    .expect("An error occurred while writing to a file.");
    return file;
}

pub fn new(args: Vec<String>) {
    let file_name: String = get_file_name(args);
    println!("got file name: {}", file_name);
    init_file(file_name);
}
