use std::fs::File;
use std::io::{stdin, Write};
use std::path::Path;

// get_file_extension will return the file extension used for checklists
pub fn get_file_extension() -> String {
    return ".chklst".to_string();
}

fn ask_name() -> String {
    println!(
        "Enter the name for the checklist (will have {} appended): ",
        get_file_extension()
    );
    let mut input = String::new();

    stdin().read_line(&mut input).expect("Invalid input");
    return input.trim().to_string();
}

fn get_file_name(args: Vec<String>) -> String {
    let file_name: String;
    if args.len() > 2 {
        file_name = args[2].to_string();
    } else {
        file_name = ask_name();
    }
    return String::from(file_name + &get_file_extension());
}

fn init_file(file_name: String) -> Option<std::fs::File> {
    if Path::new(&file_name).exists() {
        println!(
            "File already exists: {}{}",
            file_name, ". The file was not overwritten."
        );
        return None;
    }
    let mut file = File::create(file_name).expect("Error occurred while creating file.");
    file.write_all(
        b"This is an auto-generated checklist made by todo-tracker.\n\nDo not edit this file.",
    )
    .expect("An error occurred while writing to a file.");
    println!("File created successfully.");
    return Some(file);
}

pub fn new(args: Vec<String>) {
    let file_name: String = get_file_name(args);
    init_file(file_name);
}
